/* Generated By:JavaCC: Do not edit this line. Scanner_1Constants.java */
package Compiladores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Scanner_1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int COMENTARIOS = 6;
  /** RegularExpression Id. */
  int COM = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int AP = 11;
  /** RegularExpression Id. */
  int FP = 12;
  /** RegularExpression Id. */
  int AC = 13;
  /** RegularExpression Id. */
  int FC = 14;
  /** RegularExpression Id. */
  int ASGN = 15;
  /** RegularExpression Id. */
  int V = 16;
  /** RegularExpression Id. */
  int PV = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int DOUBLE = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int VDOUBLE = 22;
  /** RegularExpression Id. */
  int VCHAR = 23;
  /** RegularExpression Id. */
  int VINT = 24;
  /** RegularExpression Id. */
  int SOMA = 25;
  /** RegularExpression Id. */
  int SUBT = 26;
  /** RegularExpression Id. */
  int INVALIDO_LEXICO = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO>",
    "<COMENTARIOS>",
    "<COM>",
    "\"begin\"",
    "<DIGIT>",
    "<ID>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"INT\"",
    "\"FLOAT\"",
    "\"DOUBLE\"",
    "\"CHAR\"",
    "<VDOUBLE>",
    "<VCHAR>",
    "<VINT>",
    "\"+\"",
    "\"-\"",
    "<INVALIDO_LEXICO>",
  };

}
